---
- name: install httpd
  become: true
  become_method: sudo
  become_user: root
  gather_facts: true
  hosts: all
  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: latest
    - name: httpd is running
      service:
        name: httpd
        state: started
        enable: true
...
