---
- name: Deploy the web servers
  hosts: all
  become: True
  gather_facts: False
  tasks:
    - name: ensure required package is installed
      yum:
        name:
          - httpd
          - mod_ssl
          - httpd-tools
          - mariadb-server
          - mariadb
          - php
          - php-mysqlnd
        state: absent
