---
- name: Deploy the web servers
  hosts: all
  become: True
  gather_facts: False
  pre_tasks:
    - name: setting the maintenance message
      copy:
        dest: /tmp/site.ready
        content: "Playbook site.yaml is ready to start"
  tasks:
    - name: ensure required package is installed
      yum:
        name:
          - httpd
          - mod_ssl
          - httpd-tools
          - mariadb-server
          - mariadb
          - php
          - php-mysqlnd
        state: present
    - name: ensure the services are enabled
      service:
        name: "{{ item }}"
        state: started
        enabled: True
      loop:
        - httpd
        - mariadb
    - name: ensure the web content is installed
      synchronize:
        src: web_content
        dest: /var/www/html
