---
- name: install and enable httpd service
  hosts: all_servers
  become_user: root
  become_method: sudo
  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: latest
    - name: start httpd
      ansible.builtin.service:
        name: httpd
        state: started
