---
- name: install httpd service
  hosts: all
  become: true
  become_user: root
  become_method: sudo
  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: latest
    - name: execute all notified handlers
      meta: flush_handlers
    - name: include role
      include_role:
        name: httpd_role
    - name: enable httpd service
      ansible.builtin.service:
        name: httpd
        state: started
...
