---
- name: install httpd service
  hosts: managedh1
  become: false
  gather_facts: no
  tags:
    - setup
  roles:
    - role: httpdDeploy
      tags:
        - production
        - staging
  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: latest
      become: true
      tags:
        - install
    - name: execute all notified handlers
      meta: flush_handlers
    - name: enable httpd service
      ansible.builtin.service:
        name: httpd
        state: started
...
